---
# tasks file for user_manage
- name: Create group
  group:
    name: "ansibleusers"
    state: present

- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512')}}"
    groups: "ansibleusers"
    append: yes
  with_items: "{{ users }}"
  when: item.state == 'present'

- name: Deploy SSH keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items: "{{ users }}"
  when: item.state == 'present'

  