---
# tasks file for user_manage
- name: Create group
  group:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ group }}"
  when: item.state == 'present'

- name: Create users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512')}}"
    groups: "ansibleusers"
    append: yes
  with_items: "{{ users }}"
  when: item.state == "present"

- name: Deploy SSH keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key }}"
  with_items: "{{ users }}"
  when: item.state == "present"

- name: Delete users
  user:
    name: "{{ item.name }}"
    state: absent
    remove: yes
  with_items: "{{ users }}"

- name: Delete groups
  group:
    name: "{{ item.name }}"
    state: absent
  with_items: "{{ group }}"


  